package store

import "errors"

var (
	ErrNotFound              = errors.New("not found")
	ErrUsernameTaken         = errors.New("username taken")
	ErrAliasTaken            = errors.New("alias already in use")
	ErrEmailTaken            = errors.New("email already in use")
	ErrBadDayDuration        = errors.New("day duration must be between 60 and 86400 seconds")
	ErrRoomEnded             = errors.New("room has ended")
	ErrRoomNotRunning        = errors.New("room is not running")
	ErrAlreadyJoined         = errors.New("already joined this room")
	ErrCannotStart           = errors.New("room can only be started by its host while in lobby")
	ErrNotStarted            = errors.New("room not started")
	ErrBadOrder              = errors.New("invalid order")
	ErrUnknownInstrument     = errors.New("unknown instrument")
	ErrInsufficientCash      = errors.New("insufficient cash")
	ErrInsufficientShares    = errors.New("insufficient shares")
	ErrNotCancellable        = errors.New("order cannot be cancelled")
	ErrBadChatMessage        = errors.New("chat message must be 1-500 characters")
	ErrPlayerBankrupt        = errors.New("player is bankrupt")
	ErrBadLoanAmount         = errors.New("invalid loan amount")
	ErrDebtCapExceeded       = errors.New("borrow would exceed the debt cap")
	ErrBadOptionOrder        = errors.New("invalid option order")
	ErrInsufficientContracts = errors.New("insufficient option contracts")
	ErrBadAction             = errors.New("invalid action")
	ErrActionLimit           = errors.New("daily action limit reached")
	ErrAlreadyDisputed       = errors.New("news item already disputed")
	ErrBadProfile            = errors.New("display name and avatar are required")
	ErrBadRoomName           = errors.New("room name must be 2-40 visible characters")
	ErrBadVisibility         = errors.New("room visibility must be public or private")
	ErrPublicJoinClosed      = errors.New("this public room is no longer open for joining")
	ErrRoomFull              = errors.New("this room is full")
)
