ALTER TABLE scenarios ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE scenarios ADD COLUMN real_period TEXT NOT NULL DEFAULT '';
ALTER TABLE room_news ADD COLUMN cluster_id BIGINT NOT NULL DEFAULT 0;
