package pipeline

// crash1987FetchSpecs: the 1987-era (crash-1987) contribution to `pipeline
// fetch`'s download list. Every name here is deduped against the other
// universes' FetchSpecs by `pipeline fetch` (union by Name), so listing
// shared symbols (ko/mcd/dis/jnj/pg/mmm/cat/ibm/hpq/ge/xom/wmt/spx) again
// here — even though dotcom-2000/universe_dotcom.go already lists most of
// them with a wider From/To — is correct: it documents which universes
// actually consume each file, mirroring the shared-symbol convention.
//
// mrk/ba/axp are this universe's own symbols, moved here during plan-5
// Task 3 when they were fetched ahead of this universe's existence.
//
// Y16 (dji, Legacy Bluechip Index/道琼斯工业指数) is DROPPED per controller ruling: ^DJI has
// no pre-1992 daily history on Yahoo's chart API (verified against several
// period1 values spanning 1970-1985, every one returns the same 1992-01-02
// first bar; see the dji entry doc in universe_2008.go for the full detail),
// which is after this scenario's entire 1986-1988 window. This universe
// has 16 instruments (Y01..Y15, Y17); Y17 remains "Y17" (MarketProxy) per
// the controller's explicit instruction not to renumber.
var crash1987FetchSpecs = []FetchSpec{
	{Name: "ko", Symbol: "KO", From: "1970-06-01", To: "1989-06-30"},
	{Name: "mcd", Symbol: "MCD", From: "1970-06-01", To: "2010-06-30"},
	{Name: "dis", Symbol: "DIS", From: "1970-06-01", To: "1989-06-30"},
	{Name: "jnj", Symbol: "JNJ", From: "1970-06-01", To: "1989-06-30"},
	{Name: "pg", Symbol: "PG", From: "1970-06-01", To: "1989-06-30"},
	{Name: "mmm", Symbol: "MMM", From: "1970-06-01", To: "1989-06-30"},
	{Name: "cat", Symbol: "CAT", From: "1970-06-01", To: "1989-06-30"},
	{Name: "ibm", Symbol: "IBM", From: "1970-06-01", To: "2002-03-31"},
	{Name: "hpq", Symbol: "HPQ", From: "1985-06-01", To: "2002-03-31"},
	{Name: "ge", Symbol: "GE", From: "1985-06-01", To: "2010-06-30"},
	// xom: widened to 1970-06-01 by nifty-1972 (Task 5) — its N13 needs the
	// file back to 1972-01-03; kept identical here so FetchSpec dedup by
	// Name (cmd/pipeline's unionFetchSpecs) never depends on registration
	// order across universes.
	{Name: "xom", Symbol: "XOM", From: "1970-06-01", To: "2010-06-30"},
	{Name: "wmt", Symbol: "WMT", From: "1985-06-01", To: "2010-06-30"},
	{Name: "spx", Symbol: "^GSPC", From: "1970-06-01", To: "2010-06-30"},
	// This universe's own symbols, moved off pendingFetchSpecs.
	{Name: "mrk", Symbol: "MRK", From: "1985-06-01", To: "1989-06-30"},
	{Name: "ba", Symbol: "BA", From: "1985-06-01", To: "1989-06-30"},
	{Name: "axp", Symbol: "AXP", From: "1985-06-01", To: "1989-06-30"},
}

var crash1987Universe = ScenarioUniverse{
	ScenarioID:  "crash-1987",
	Name:        "1987 黑色星期一",
	NameEn:      "1987 Black Monday",
	RealPeriod:  "1986-01 ~ 1988-12",
	EraHint:     "类似程序化交易与并购热潮推起大牛市的年代",
	WindowStart: "1986-01-02",
	WindowEnd:   "1988-12-30",
	MarketProxy: "Y17",
	FetchSpecs:  crash1987FetchSpecs,
	Sectors: []SectorSpec{
		{ID: "IND", Name: "工业制造", NameEn: "Industrial Manufacturing"},
		{ID: "CONS", Name: "消费品牌", NameEn: "Consumer Brands"},
		{ID: "PHRM", Name: "医药", NameEn: "Pharmaceuticals"},
		{ID: "TECH", Name: "计算机", NameEn: "Computers"},
		{ID: "FIN", Name: "金融", NameEn: "Financials"},
		{ID: "ENGY", Name: "能源", NameEn: "Energy"},
		{ID: "RETL", Name: "零售", NameEn: "Retail"},
	},
	Macros: []SectorSpec{
		{ID: "GOLD", Name: "黄金", NameEn: "Gold"},
		{ID: "OIL", Name: "原油", NameEn: "Crude Oil"},
		{ID: "RATE", Name: "利率", NameEn: "Interest Rates"},
	},
	KeyWindows: []DateWindow{
		{"1987-01-02", "1987-08-25", 1},  // 疯牛期，压制逆势冷水
		{"1987-10-14", "1987-10-30", -1}, // 崩盘周
	},
	Instruments: []InstrumentSpec{
		{ID: "Y01", Raw: "ibm", Sector: "TECH",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.3},
			Dossier: Dossier{Alias: "Atlas Computing Corp.", Aliases: []string{"Atlas Computing Corp.", "Dominion Computing", "Union Data Systems"}, Desc: "百年计算公司", RealName: "IBM",
				DescEn:     "A century-old computing company",
				Business:   "大型机、系统与服务三驾马车，企业后台离不开它的机器。",
				BusinessEn: "Mainframes, systems, and services as its three engines; corporate back offices can't run without its machines.",
				Bull:       "并购与回购热潮里现金牛最抗跌，蓝筹信仰历久弥新。",
				BullEn:     "In a wave of mergers and buybacks, cash cows hold up best; faith in blue chips endures.",
				Bear:       "大型机的增长故事讲了太多年，新一代小型机器正在啃它的市场。",
				BearEn:     "The mainframe growth story has been told for too many years, and a new generation of smaller machines is eating its market."}},
		{ID: "Y02", Raw: "hpq", Sector: "TECH",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.3},
			Dossier: Dossier{Alias: "Camberwell Instruments", Aliases: []string{"Camberwell Instruments", "Testpoint Instruments", "Greybar Instruments"}, Desc: "老牌硅谷仪器厂", RealName: "Hewlett-Packard",
				DescEn:     "A veteran Silicon Valley instrument maker",
				Business:   "从实验室仪器起家，如今靠打印机与工作站两条腿走路。",
				BusinessEn: "Born in laboratory instruments, it now walks on two legs: printers and workstations.",
				Bull:       "工程师文化做出来的产品口碑扎实，办公室自动化浪潮才刚开始。",
				BullEn:     "Products built on an engineering culture have a solid reputation, and the office-automation wave has only just begun.",
				Bear:       "仪器业务增长见顶，新业务能否接棒还是问号。",
				BearEn:     "The instrument business's growth has peaked; whether the new businesses can take over is an open question."}},
		{ID: "Y03", Raw: "ko", Sector: "CONS",
			ExtraBeta: map[string]float64{"SENT": 0.45, "RATE": -0.25},
			Dossier: Dossier{Alias: "Harborline Beverages", Aliases: []string{"Harborline Beverages", "Fountainhead Beverages", "Arcadia Bottling Co."}, Desc: "全球装瓶的饮料霸主", RealName: "Coca-Cola",
				DescEn:     "The global bottling beverage overlord",
				Business:   "一瓶糖水卖遍全球的品牌机器，装瓶网络深入每个国家的毛细血管。",
				BusinessEn: "A brand machine selling a bottle of sugared water worldwide, its bottling network reaching into every country's capillaries.",
				Bull:       "品牌就是复利：只要人还口渴，提价权与全球化就是双引擎，牛市里机构最安心的核心持仓。",
				BullEn:     "A brand is compound interest: as long as people get thirsty, pricing power and globalization are twin engines — the core holding institutions trust most in a bull market.",
				Bear:       "所有人都安心的持仓，估值早已不便宜；当组合保险开始机械抛售时，最拥挤的地方跌得最快。",
				BearEn:     "A holding everyone trusts is no longer cheap; when portfolio insurance starts selling mechanically, the most crowded places fall fastest."}},
		{ID: "Y04", Raw: "pg", Sector: "CONS",
			ExtraBeta: map[string]float64{"SENT": 0.35, "RATE": -0.25},
			Dossier: Dossier{Alias: "Willowbrook Consumer Goods", Aliases: []string{"Willowbrook Consumer Goods", "Homespun Consumer Brands", "Candlewick Household Goods"}, Desc: "百年日化帝国", RealName: "Procter & Gamble",
				DescEn:     "A century-old household-goods empire",
				Business:   "牙膏、洗衣粉、纸尿裤——货架上一堆你叫不出集团名字的日用品都是它的。",
				BusinessEn: "Toothpaste, laundry detergent, diapers — half the everyday goods on the shelf whose parent name you couldn't recite are its.",
				Bull:       "消费品里最无聊也最稳的现金流，牛市里当压舱石照样跟涨。",
				BullEn:     "The most boring and steadiest cash flow in consumer goods; as ballast it still rises with the bull.",
				Bear:       "增长全靠货架份额一点点抢，讲不出让人兴奋的新故事。",
				BearEn:     "Growth comes from clawing shelf share inch by inch; there is no exciting new story to tell."}},
		{ID: "Y05", Raw: "mcd", Sector: "CONS",
			ExtraBeta: map[string]float64{"SENT": 0.45, "RATE": -0.25},
			Dossier: Dossier{Alias: "Roadside Restaurant Group", Aliases: []string{"Roadside Restaurant Group", "Burgerlane Group", "Corner Restaurant Systems"}, Desc: "全球连锁快餐之王", RealName: "McDonald's",
				DescEn:     "The king of global fast-food chains",
				Business:   "标准化流程复制到全球的连锁快餐，加盟费与地产租金才是真正的利润引擎。",
				BusinessEn: "A standardized fast-food formula replicated worldwide; franchise fees and real-estate rents are the true profit engine.",
				Bull:       "开一家新店就多一份稳定现金流，扩张速度就是股价的发动机。",
				BullEn:     "Every new store adds another stream of steady cash flow; expansion speed is the stock's engine.",
				Bear:       "同店销售增速终会撞天花板，加盟商的抱怨迟早传到股东耳朵里。",
				BearEn:     "Same-store sales growth will eventually hit a ceiling, and franchisees' grumbling will reach shareholders' ears sooner or later."}},
		{ID: "Y06", Raw: "dis", Sector: "CONS",
			ExtraBeta: map[string]float64{"SENT": 0.45, "RATE": -0.25},
			Dossier: Dossier{Alias: "Silverglade Entertainment", Aliases: []string{"Silverglade Entertainment", "Storybook Entertainment", "Parkgate Amusements"}, Desc: "动画起家的娱乐帝国", RealName: "Disney",
				DescEn:     "An entertainment empire built on animation",
				Business:   "老牌动画厂靠乐园门票、周边授权和新片接力撑起收入。",
				BusinessEn: "A veteran animation studio supported by theme-park tickets, merchandise licensing, and a relay of new films.",
				Bull:       "新管理层重新点燃创意引擎，乐园涨价照样人潮涌动。",
				BullEn:     "New management has relit the creative engine, and the parks stay packed even as ticket prices rise.",
				Bear:       "内容生意大小年明显，一部大片扑街就要等下一部救场。",
				BearEn:     "Content is a hit-driven business; one blockbuster flop means waiting for the next film to save the day."}},
		{ID: "Y07", Raw: "mrk", Sector: "PHRM",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.25},
			Dossier: Dossier{Alias: "Vireo Therapeutics", Aliases: []string{"Vireo Therapeutics", "Curewell Labs", "Pennington Pharmaceuticals"}, Desc: "研发驱动的大药厂", RealName: "Merck",
				DescEn:     "An R&D-driven pharmaceutical giant",
				Business:   "重金投入研发管线，靠专利期内的爆款处方药收割高毛利。",
				BusinessEn: "Heavy investment in the research pipeline, harvesting high margins from blockbuster prescription drugs inside their patent windows.",
				Bull:       "老龄化与慢性病是永续需求，专利护城河让定价权稳如泰山。",
				BullEn:     "Aging and chronic disease are perpetual demand, and the patent moat keeps pricing power rock-solid.",
				Bear:       "专利总有到期日，管线一旦断档增长立刻熄火。",
				BearEn:     "Every patent has an expiry date; the moment the pipeline runs dry, growth stalls."}},
		{ID: "Y08", Raw: "jnj", Sector: "PHRM",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.25},
			Dossier: Dossier{Alias: "Wellmark Health Group", Aliases: []string{"Wellmark Health Group", "Familycare Health Group", "Gentlebrook Health"}, Desc: "从婴儿爽身粉到手术缝线", RealName: "Johnson & Johnson",
				DescEn:     "From baby powder to surgical sutures",
				Business:   "婴儿护理、医疗器械、处方药三条业务线同时下注，风险天然分散。",
				BusinessEn: "Three bets at once — baby care, medical devices, prescription drugs — with risk diversified by design.",
				Bull:       "东边不亮西边亮，多元业务组合让业绩曲线格外平滑。",
				BullEn:     "When one side dims, another shines; the diversified mix makes the earnings curve exceptionally smooth.",
				Bear:       "分散也意味着没有一条业务能真正引领增长，故事讲不出爆点。",
				BearEn:     "Diversification also means no single business can truly lead growth; the story has no punch line."}},
		{ID: "Y09", Raw: "mmm", Sector: "IND",
			ExtraBeta: map[string]float64{"SENT": 0.25, "RATE": -0.45},
			Dossier: Dossier{Alias: "Stratford Materials", Aliases: []string{"Stratford Materials", "Polywright Materials", "Gritstone Industries"}, Desc: "什么都能粘的材料公司", RealName: "3M",
				DescEn:     "A materials company that can stick anything",
				Business:   "从胶带到研磨材料，几千种工业与办公产品共享同一套材料科学底子。",
				BusinessEn: "From tape to abrasives, thousands of industrial and office products share one materials-science foundation.",
				Bull:       "产品线极度分散，只要工厂在开工它总有一样东西被买走。",
				BullEn:     "The product line is so dispersed that as long as factories are running, something of its is always being bought.",
				Bear:       "工业周期一旦转冷，资本开支收缩会传导到它的每一条产品线。",
				BearEn:     "Once the industrial cycle cools, shrinking capital spending transmits to every one of its product lines."}},
		{ID: "Y10", Raw: "ba", Sector: "IND",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.45},
			Dossier: Dossier{Alias: "Continental Aerospace", Aliases: []string{"Continental Aerospace", "Jetstream Aerospace", "Airframe Dynamics"}, Desc: "民航客机双雄之一", RealName: "Boeing",
				DescEn:     "One of the two makers of passenger jets",
				Business:   "长周期的商用客机制造，订单排到数年后，交付节奏决定利润节奏。",
				BusinessEn: "Long-cycle commercial aircraft manufacturing; orders are booked years out, and delivery cadence sets the profit cadence.",
				Bull:       "航空旅行需求长期向上，积压订单就是未来好几年的收入保证。",
				BullEn:     "Air-travel demand rises over the long term, and the order backlog guarantees several years of revenue.",
				Bear:       "订单周期长意味着景气反转要等很久才能显现，且取消订单代价高昂。",
				BearEn:     "Long order cycles mean downturns take ages to show up, and cancellations are costly."}},
		{ID: "Y11", Raw: "cat", Sector: "IND",
			ExtraBeta: map[string]float64{"SENT": 0.25, "RATE": -0.5},
			Dossier: Dossier{Alias: "Ironfield Heavy Industries", Aliases: []string{"Ironfield Heavy Industries", "Earthmover Industries", "Granite Heavy Equipment"}, Desc: "推土机与矿山机械之王", RealName: "Caterpillar",
				DescEn:     "The king of bulldozers and mining machinery",
				Business:   "工地与矿场少不了的重型机械，经销商网络铺满全球每一片工地。",
				BusinessEn: "Heavy machinery no construction site or mine can do without, its dealer network covering every worksite on earth.",
				Bull:       "基建与资源开发是长期趋势，重型设备折旧完了还得再买新的。",
				BullEn:     "Infrastructure and resource development are long-term trends, and worn-out heavy equipment must be replaced.",
				Bear:       "重资产、高杠杆的周期股，利率一抬头，工地的挖机订单第一个被砍。",
				BearEn:     "An asset-heavy, high-leverage cyclical; the moment rates tick up, excavator orders are the first to be cut."}},
		{ID: "Y12", Raw: "ge", Sector: "IND",
			ExtraBeta: map[string]float64{"SENT": 0.3, "RATE": -0.45},
			Dossier: Dossier{Alias: "Concord Industrial Group", Aliases: []string{"Concord Industrial Group", "Dynamo Industrial Group", "Trustworth Industries"}, Desc: "什么都造的工业帝国", RealName: "General Electric",
				DescEn:     "An industrial empire that makes everything",
				Business:   "发电机、飞机引擎、医疗设备加一个庞大的金融部门，业务横跨所有周期。",
				BusinessEn: "Generators, aircraft engines, medical equipment, plus a huge finance arm — spanning every cycle.",
				Bull:       "传奇管理层治下利润从不失手，机构的压舱石首选。",
				BullEn:     "Under legendary management, profits never miss — institutions' ballast of choice.",
				Bear:       "金融部门的杠杆是报表深处的暗礁，'从不失手'本身就值得怀疑。",
				BearEn:     "The finance arm's leverage is a reef deep in the statements, and 'never misses' is itself suspicious."}},
		{ID: "Y13", Raw: "axp", Sector: "FIN",
			ExtraBeta: map[string]float64{"SENT": 0.35, "RATE": -0.5},
			Dossier: Dossier{Alias: "Marquis Financial Services", Aliases: []string{"Marquis Financial Services", "Prestige Card Services", "Voyager Financial"}, Desc: "高端签账卡与旅行支票", RealName: "American Express",
				DescEn:     "Premium charge cards and traveler's checks",
				Business:   "高端客群的签账卡与旅行支票生意，赚的是商户回佣与浮存金。",
				BusinessEn: "A charge-card and traveler's-check business for affluent customers, earning merchant fees and float.",
				Bull:       "消费升级的年代，绿色卡片是身份的通行证，会员费提了又提照样排队。",
				BullEn:     "In an age of consumption upgrades, the card is a passport to status; the membership fee rises and rises, and people still line up.",
				Bear:       "利率一抬头，浮存金优势缩水；金融股在恐慌里从没当过避风港。",
				BearEn:     "When rates rise the float advantage shrinks, and financials have never been a haven in a panic."}},
		{ID: "Y14", Raw: "xom", Sector: "ENGY",
			ExtraBeta: map[string]float64{"SENT": 0.2, "RATE": -0.25, "OIL": 0.6, "GOLD": 0.1},
			Dossier: Dossier{Alias: "Bastion Petroleum", Aliases: []string{"Bastion Petroleum", "Tankerline Petroleum", "Seacoast Petroleum"}, Desc: "全球油气巨轮", RealName: "Exxon",
				DescEn:     "A global oil-and-gas supertanker",
				Business:   "从油井到加油站的全产业链油气巨头，规模冠绝全球同行。",
				BusinessEn: "A fully integrated oil-and-gas giant from wellhead to gas station, scale unmatched among global peers.",
				Bull:       "无论景气与否，人总要开车取暖；恐慌时现金流是最硬的叙事。",
				BullEn:     "Boom or bust, people still drive and heat their homes; in a panic, cash flow is the hardest narrative.",
				Bear:       "油价下行周期里巨轮也得随波逐流，牛市狂热年代反而常常跑输大盘。",
				BearEn:     "In an oil-price downcycle even supertankers drift with the tide, and in manic bull years it often lags the market."}},
		{ID: "Y15", Raw: "wmt", Sector: "RETL",
			ExtraBeta: map[string]float64{"SENT": 0.4, "RATE": -0.3},
			Dossier: Dossier{Alias: "Plainfield Stores", Aliases: []string{"Plainfield Stores", "Pricewise Stores", "Countrymart"}, Desc: "乡镇起家的零售之王", RealName: "Walmart",
				DescEn:     "The retail king from small-town roots",
				Business:   "天天低价的连锁超市帝国，供应链效率碾压一切同行。",
				BusinessEn: "An everyday-low-price supermarket empire whose supply-chain efficiency crushes every rival.",
				Bull:       "从乡镇一路开进大城市，门店扩张曲线还远没走完。",
				BullEn:     "It has marched from small towns into big cities, and the store-expansion curve is far from finished.",
				Bear:       "低毛利模式对成本敏感，扩张太快也容易踩到管理短板。",
				BearEn:     "The low-margin model is cost-sensitive, and expanding too fast exposes management's weak spots."}},
		{ID: "Y17", Raw: "spx", Sector: "",
			ExtraBeta: map[string]float64{"SENT": 0.5, "RATE": -0.35},
			Dossier: Dossier{Alias: "Premier 500 Index", Aliases: []string{"Premier 500 Index", "Benchmark 500 Index", "Guardian 500 Index"}, Desc: "五百家大公司的市值加权指数", RealName: "S&P 500 指数",
				DescEn:     "A cap-weighted index of five hundred large companies",
				Business:   "五百家大公司的市值加权组合，一笔交易买下整个经济的横截面。",
				BusinessEn: "A market-cap-weighted basket of five hundred large companies — a cross-section of the whole economy in one trade.",
				Bull:       "不赌个股不赌行业，赌整体经济的长期向上。",
				BullEn:     "Bet on no stock and no sector; bet on the economy's long-term rise.",
				Bear:       "指数里挤满了同一批热门蓝筹，程序化抛售一来谁都躲不掉。",
				BearEn:     "The index is crowded with the same hot blue chips; when program selling hits, nobody escapes."}},
	},
}

func init() {
	Register(&crash1987Universe)
}
